# Generated by Django 5.1.6 on 2025-03-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_student_options_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
